name: flutter_model_cache
description: A local cache for models that are accessed over json apis.
version: 0.0.3
repository: https://github.com/diarmuidr3d/flutter_model_cache

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  test: ^1.25.0
  flutter_test:
    sdk: flutter
